"""SiteGuard Report Generator — produces beautiful HTML and terminal output."""

from pathlib import Path
from siteguard.scanner import ScanSummary, ScanResult


def generate_terminal_report(summary: ScanSummary) -> str:
    """Generate a beautiful terminal report using ANSI colors."""
    try:
        from colorama import Fore, Style, init
        init()
        G = Fore.GREEN; R = Fore.RED; Y = Fore.YELLOW
        C = Fore.CYAN; M = Fore.MAGENTA; W = Fore.WHITE
        B = Style.BRIGHT; RESET = Style.RESET_ALL
    except ImportError:
        G = R = Y = C = M = W = B = RESET = ""

    lines = []
    lines.append(f"{B}{C}{'═' * 60}{RESET}")
    lines.append(f"{B}{C}  🛡️  SITEGUARD SECURITY REPORT{RESET}")
    lines.append(f"{B}{C}{'═' * 60}{RESET}")
    lines.append(f"")
    lines.append(f"  {B}Target:{RESET}      {summary.target}")
    lines.append(f"  {B}Scan Time:{RESET}   {summary.scan_time}")
    lines.append(f"  {B}Checks Run:{RESET}  {summary.total_checks}")
    lines.append(f"  {B}Grade:{RESET}       {_grade_color(summary.grade, G, R, Y, RESET, B)}")
    lines.append(f"  {B}Score:{RESET}       {summary.score}")
    lines.append(f"")

    # Group by category
    categories = {}
    for r in summary.results:
        categories.setdefault(r.category, []).append(r)

    for cat, results in categories.items():
        cat_label = {"ssl": "🔒 SSL/TLS", "headers": "📋 Security Headers",
                      "owasp": "🛡️ OWASP Top 10", "exposed": "📁 Exposed Files"}.get(cat, cat)
        lines.append(f"{B}{C}▸ {cat_label}{RESET}")

        for r in results:
            status = f"{G}✅ PASS{RESET}" if r.passed else f"{R}❌ FAIL{RESET}"
            lines.append(f"  {status}  {r.title}")
            if not r.passed:
                lines.append(f"         {Y}Fix:{RESET} {r.remediation[:120]}")

    # Summary
    lines.append(f"")
    lines.append(f"{B}{C}{'═' * 60}{RESET}")
    lines.append(f"  {G}✅ Passed: {summary.passed}{RESET}  |  {R}❌ Failed: {summary.failed}{RESET}")
    lines.append(f"  {B}Overall Grade: {_grade_color(summary.grade, G, R, Y, RESET, B)}{RESET}")
    lines.append(f"{B}{C}{'═' * 60}{RESET}")
    lines.append(f"")
    lines.append(f"  Report generated by SiteGuard v1.0.0")
    lines.append(f"  github.com/adbhutrd/siteguard")
    lines.append(f"")

    return "\n".join(lines)


def generate_html_report(summary: ScanSummary) -> str:
    """Generate a professional HTML report."""
    template_path = Path(__file__).parent / "templates" / "report.html"
    if template_path.exists():
        template = template_path.read_text()
    else:
        template = _get_builtin_template()

    # Build findings HTML
    findings_html = ""
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_results = sorted(summary.results, key=lambda r: severity_order.get(r.severity, 5))

    for r in sorted_results:
        status_class = "pass" if r.passed else "fail"
        severity_class = f"severity-{r.severity}"
        findings_html += f"""
        <div class="finding {status_class} {severity_class}">
            <div class="finding-header">
                <span class="finding-status">{'✅' if r.passed else '❌'}</span>
                <span class="finding-title">{r.title}</span>
                <span class="finding-severity">{r.severity.upper()}</span>
            </div>
            <div class="finding-body">
                <p>{r.description}</p>
                {f'<div class="remediation"><strong>🔧 Fix:</strong> {r.remediation}</div>' if not r.passed else ''}
                {f'<div class="evidence"><strong>📋 Evidence:</strong> <code>{r.evidence}</code></div>' if r.evidence else ''}
            </div>
        </div>"""

    # Grade color
    grade_colors = {
        "A+": "#22c55e", "A": "#22c55e", "B": "#3b82f6",
        "C": "#f59e0b", "D": "#f97316", "F": "#ef4444",
    }
    grade_color = grade_colors.get(summary.grade, "#888")

    # Replace template variables
    html = template
    html = html.replace("{{TARGET}}", summary.target)
    html = html.replace("{{SCAN_TIME}}", summary.scan_time)
    html = html.replace("{{TOTAL_CHECKS}}", str(summary.total_checks))
    html = html.replace("{{PASSED}}", str(summary.passed))
    html = html.replace("{{FAILED}}", str(summary.failed))
    html = html.replace("{{GRADE}}", summary.grade)
    html = html.replace("{{SCORE}}", summary.score)
    html = html.replace("{{GRADE_COLOR}}", grade_color)
    html = html.replace("{{FINDINGS}}", findings_html)

    return html


def _grade_color(grade: str, G, R, Y, RESET, B) -> str:
    """Get color for grade."""
    if grade in ("A+", "A"):
        return f"{G}{B}{grade}{RESET}"
    elif grade == "B":
        return f"{B}{grade}{RESET}"
    elif grade in ("C", "D"):
        return f"{Y}{B}{grade}{RESET}"
    else:
        return f"{R}{B}{grade}{RESET}"


def _get_builtin_template() -> str:
    """Builtin HTML template (used when template file is missing)."""
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SiteGuard Report — {{TARGET}}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0a0a0f;color:#e1e1e6;line-height:1.6;padding:20px}
.container{max-width:900px;margin:0 auto}
.header{text-align:center;padding:40px 20px;border-bottom:1px solid rgba(255,255,255,0.08);margin-bottom:30px}
.header h1{font-size:32px;font-weight:800;background:linear-gradient(135deg,#7c3aed,#3b82f6);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.header .meta{color:#888;margin-top:8px;font-size:14px}
.score-card{display:flex;align-items:center;justify-content:center;gap:24px;padding:30px;background:#12121c;border:1px solid rgba(255,255,255,0.06);border-radius:16px;margin-bottom:30px;flex-wrap:wrap}
.grade-circle{width:100px;height:100px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:48px;font-weight:800;color:white;background:{{GRADE_COLOR}};box-shadow:0 8px 30px rgba(0,0,0,0.3)}
.stats{text-align:left}
.stats .stat{margin:8px 0;font-size:14px}
.stats .stat strong{color:#e1e1e6}
.stats .passed{color:#22c55e}.stats .failed{color:#ef4444}
.finding{background:#12121c;border:1px solid rgba(255,255,255,0.06);border-radius:12px;padding:20px;margin-bottom:12px}
.finding.fail{border-left:3px solid #ef4444}
.finding.pass{border-left:3px solid #22c55e}
.finding-header{display:flex;align-items:center;gap:12px;margin-bottom:10px}
.finding-status{font-size:20px}
.finding-title{font-weight:600;flex:1}
.finding-severity{font-size:11px;font-weight:700;padding:3px 10px;border-radius:100px;text-transform:uppercase}
.severity-critical{background:rgba(239,68,68,0.1);color:#ef4444;border:1px solid rgba(239,68,68,0.2)}
.severity-high{background:rgba(249,115,22,0.1);color:#f97316;border:1px solid rgba(249,115,22,0.2)}
.severity-medium{background:rgba(245,158,11,0.1);color:#f59e0b;border:1px solid rgba(245,158,11,0.2)}
.severity-low{background:rgba(59,130,246,0.1);color:#3b82f6;border:1px solid rgba(59,130,246,0.2)}
.severity-info{background:rgba(34,197,94,0.1);color:#22c55e;border:1px solid rgba(34,197,94,0.2)}
.finding-body p{font-size:13px;color:#888;margin-bottom:8px}
.remediation{background:rgba(249,115,22,0.06);padding:10px 14px;border-radius:8px;font-size:13px;margin-top:8px;border:1px solid rgba(249,115,22,0.15)}
.evidence{font-size:12px;color:#666;margin-top:8px}
.evidence code{background:rgba(0,0,0,0.3);padding:2px 6px;border-radius:4px}
.footer{text-align:center;padding:30px;color:#555;font-size:12px;margin-top:30px;border-top:1px solid rgba(255,255,255,0.06)}
</style>
</head>
<body>
<div class="container">
<div class="header">
<h1>🛡️ SiteGuard Security Report</h1>
<p class="meta">Target: <strong>{{TARGET}}</strong> • Scanned: {{SCAN_TIME}}</p>
</div>
<div class="score-card">
<div class="grade-circle">{{GRADE}}</div>
<div class="stats">
<div class="stat">Score: <strong>{{SCORE}}</strong></div>
<div class="stat">Checks: <strong>{{TOTAL_CHECKS}}</strong></div>
<div class="stat passed">Passed: <strong>{{PASSED}}</strong></div>
<div class="stat failed">Failed: <strong>{{FAILED}}</strong></div>
</div>
</div>
<h2 style="margin-bottom:16px">📋 Detailed Findings</h2>
{{FINDINGS}}
<div class="footer">
<p>Generated by <strong>SiteGuard v1.0.0</strong> — Free Website Security Scanner</p>
<p>github.com/adbhutrd/siteguard</p>
</div>
</div>
</body>
</html>"""
